#!/usr/bin/env sh
set -e
set -x
# Do our mini example first
cd mini-complete-example
./sbt/sbt clean compile package
./sbt/sbt clean
echo $PWD && mvn clean && mvn compile
cd ..
# Run the tests
export SPARK_HOME=./spark-1.3.1-bin-hadoop1/
./sbt/sbt compile package assembly
echo $?
time ./run-all-examples
echo $?
echo "done"
# Try and build with maven, skip for now
#mvn clean && mvn compile && mvn package
